/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/neo_shades.glb 
Author: Fridge (https://sketchfab.com/youssefdarwish01)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/neo-shades-9c245663fb2141aeba813ca0d7d9bb07
Title: Neo Shades
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/neo_shades.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.NeoJacket_NeoJacket_0.geometry} material={materials.NeoJacket} position={[107.202, 28.332, 432.81]} scale={100} />
        <mesh geometry={nodes.NeoGlasses_NeoShades_0.geometry} material={materials.NeoShades} position={[116.243, 367.547, 288.452]} rotation={[1.762, 0, Math.PI]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/neo_shades.glb')
