/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/computer.glb 
Author: MadeByYeshe (https://sketchfab.com/MadeByYeshe)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-crt-computer-1990s-desktop-pc-ea9faf1298d24497b916c27a4ea38636
Title: Retro CRT Computer (1990s Desktop PC)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Computer(props) {
  const { nodes, materials } = useGLTF('/models/computer.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[1.737, 0.28, -1.524]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Object_6.geometry} material={materials.Monitor_Cream} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Monitor_Glass} />
      </group>
      <group position={[1.754, 0.075, -1.533]} rotation={[Math.PI / 2, 0, 0]} scale={0.011}>
        <mesh geometry={nodes.Object_11.geometry} material={materials.PC_Cream} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Pc_Feet} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Ucupaint_Keyboard_Creme} position={[2.035, 0.023, -1.494]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Mouse_Cream} position={[2.019, 0.022, -1.786]} rotation={[Math.PI / 2, 0, 0]} scale={0.011} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Pc_Feet} position={[2, 0.011, -1.333]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.102, 0.102, 0.102]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Pc_Feet} position={[2, 0.011, -1.783]} scale={0.102} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.Pc_Feet} position={[1.488, 0.134, -1.475]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.102, 0.102, 0.102]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Pc_Feet} position={[1.49, 0.13, -1.542]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.102, 0.102, 0.102]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.PC_Front_Cream} position={[1.754, 0.075, -1.533]} rotation={[Math.PI / 2, 0, 0]} scale={0.011} />
    </group>
  )
}

useGLTF.preload('/models/computer.glb')
