/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/panasonic_rc_6088_am.glb 
Author: Sirenko (https://sketchfab.com/sirenko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/panasonic-rc-6088-am-72801a6b5e8044a19fd14498493efc14
Title: Panasonic RC 6088 AM
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function PanasonicRc6088(props) {
  const { nodes, materials } = useGLTF('/models/panasonic_rc_6088_am.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_9.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_11.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_12.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_13.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_14.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_15.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_16.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_17.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_18.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_19.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_20.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_21.geometry} material={materials.Material__25} />
          <mesh geometry={nodes.defaultMaterial_22.geometry} material={materials.Material__25} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/panasonic_rc_6088_am.glb')
