/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/computer_opt.glb -t -T -d -o public/models/Computer.tsx 
Files: public/models/computer_opt.glb [286.29KB] > C:\dev\portfolio-web-matrix\public\models\computer_opt-transformed.glb [449.9KB] (-57%)
Author: MadeByYeshe (https://sketchfab.com/MadeByYeshe)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-crt-computer-1990s-desktop-pc-ea9faf1298d24497b916c27a4ea38636
Title: Retro CRT Computer (1990s Desktop PC)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_9: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_22: THREE.Mesh
  }
  materials: {
    Ucupaint_Keyboard_Creme: THREE.MeshStandardMaterial
    Monitor_Cream: THREE.MeshStandardMaterial
    Monitor_Glass: THREE.MeshStandardMaterial
    Mouse_Cream: THREE.MeshStandardMaterial
    PC_Cream: THREE.MeshStandardMaterial
    Pc_Feet: THREE.MeshStandardMaterial
    PC_Front_Cream: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Computer(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/computer_opt-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Ucupaint_Keyboard_Creme} position={[2.041, 0.018, -1.494]} rotation={[Math.PI / 2, 0, 0]} scale={0.213} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Monitor_Cream} position={[1.716, 0.35, -1.524]} rotation={[Math.PI / 2, 0, 0]} scale={0.212} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Monitor_Glass} position={[1.86, 0.391, -1.524]} rotation={[Math.PI / 2, 0, 0]} scale={0.147} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Mouse_Cream} position={[2.027, 0.019, -1.786]} rotation={[Math.PI / 2, 0, 0]} scale={0.049} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.PC_Cream} position={[1.658, 0.069, -1.522]} rotation={[Math.PI / 2, 0, 0]} scale={0.21} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Pc_Feet} position={[1.682, 0.13, -1.537]} rotation={[Math.PI / 2, 0, 0]} scale={0.303} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.PC_Front_Cream} position={[1.869, 0.069, -1.522]} rotation={[Math.PI / 2, 0, 0]} scale={0.212} />
    </group>
  )
}

useGLTF.preload('/models/computer_opt-transformed.glb')
