/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/hackers_basement_opt.glb -t -T -d 
Files: public/models/hackers_basement_opt.glb [24.2MB] > C:\dev\portfolio-web-matrix\hackers_basement_opt-transformed.glb [25.11MB] (-4%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    model_0: THREE.Mesh
    model_1: THREE.Mesh
    model_2: THREE.Mesh
    model_3: THREE.Mesh
    model_4: THREE.Mesh
    model_5: THREE.Mesh
    model_6: THREE.Mesh
    model_7: THREE.Mesh
    model_8: THREE.Mesh
    model_9: THREE.Mesh
    model_10: THREE.Mesh
    model_11: THREE.Mesh
    model_12: THREE.Mesh
    model_13: THREE.Mesh
    model_14: THREE.Mesh
    model_15: THREE.Mesh
    model_16: THREE.Mesh
    model_17: THREE.Mesh
    model_18: THREE.Mesh
    model_19: THREE.Mesh
    model_20: THREE.Mesh
    model_21: THREE.Mesh
    model_22: THREE.Mesh
    model_23: THREE.Mesh
    model_24: THREE.Mesh
    model_25: THREE.Mesh
    model_27: THREE.Mesh
    model_28: THREE.Mesh
    model_29: THREE.Mesh
    model_30: THREE.Mesh
    model_31: THREE.Mesh
    model_35: THREE.Mesh
    model_36: THREE.Mesh
    model_37: THREE.Mesh
    model_38: THREE.Mesh
    model_39: THREE.Mesh
    model_42: THREE.Mesh
    model_44: THREE.Mesh
    model_45: THREE.Mesh
    model_46: THREE.Mesh
    model_47: THREE.Mesh
    model_48: THREE.Mesh
    model_50: THREE.Mesh
    model_52: THREE.Mesh
    model_53: THREE.Mesh
    model_54: THREE.Mesh
    model_55: THREE.Mesh
    model_56: THREE.Mesh
    model_57: THREE.Mesh
    model_58: THREE.Mesh
    model_59: THREE.Mesh
    model_61: THREE.Mesh
    model_62: THREE.Mesh
    model_64: THREE.Mesh
    model_65: THREE.Mesh
    model_66: THREE.Mesh
    model_72: THREE.Mesh
    model_74: THREE.Mesh
    model_75: THREE.Mesh
    model_76: THREE.Mesh
    model_77: THREE.Mesh
    model_80: THREE.Mesh
    model_81: THREE.Mesh
    model_82: THREE.Mesh
    model_83: THREE.Mesh
    model_84: THREE.Mesh
    model_85: THREE.Mesh
    model_86: THREE.Mesh
    model_87: THREE.Mesh
    model_129: THREE.Mesh
    model_150: THREE.Mesh
    model_169: THREE.Mesh
    model_68: THREE.Mesh
    model_89: THREE.Mesh
  }
  materials: {
    ['Material.043']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.035']: THREE.MeshStandardMaterial
    ['Material.048']: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.046']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.034']: THREE.MeshStandardMaterial
    ['Material.049']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.030']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    ['Material.045']: THREE.MeshStandardMaterial
    ['Material.059']: THREE.MeshStandardMaterial
    ['Material.040']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.041']: THREE.MeshStandardMaterial
    ['Material.057']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    ['Material.055']: THREE.MeshStandardMaterial
    ['Material.062']: THREE.MeshStandardMaterial
    ['Material.072']: THREE.MeshStandardMaterial
    ['Material.054']: THREE.MeshStandardMaterial
    ['Material.051']: THREE.MeshStandardMaterial
    ['Material.047']: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshStandardMaterial
    ['Material.053']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.067']: THREE.MeshStandardMaterial
    ['Material.070']: THREE.MeshStandardMaterial
    ['Material.068']: THREE.MeshStandardMaterial
    ['Material.039']: THREE.MeshStandardMaterial
    ['Material.063']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.061']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.038']: THREE.MeshStandardMaterial
    ['Material.037']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.058']: THREE.MeshStandardMaterial
    ['Material.031']: THREE.MeshStandardMaterial
    ['Material.056']: THREE.MeshStandardMaterial
    ['Material.044']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.079']: THREE.MeshStandardMaterial
    ['Material.060']: THREE.MeshStandardMaterial
    ['Material.052']: THREE.MeshStandardMaterial
    ['Material.036']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.042']: THREE.MeshStandardMaterial
    ['Material.050']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.033']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
    ['Material.064']: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshPhysicalMaterial
    ['Material.066']: THREE.MeshStandardMaterial
    ['Material.075']: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function HackersBasement(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/hackers_basement_opt-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model_0.geometry} material={materials['Material.043']} position={[48.418, -3.862, 129.727]} rotation={[Math.PI / 2, 0, 0]} scale={95.662} />
      <mesh geometry={nodes.model_1.geometry} material={materials['Material.014']} position={[-149.496, 51.136, -152.055]} rotation={[Math.PI / 2, 0, 0]} scale={66.489} />
      <mesh geometry={nodes.model_2.geometry} material={materials['Material.019']} position={[-54.469, 91.093, 34.465]} rotation={[Math.PI / 2, 0, 0]} scale={192.977} />
      <mesh geometry={nodes.model_3.geometry} material={materials['Material.035']} position={[-196.145, 146.081, -67.915]} rotation={[Math.PI / 2, 0, 0]} scale={103.328} />
      <mesh geometry={nodes.model_4.geometry} material={materials['Material.048']} position={[-200.4, 150.769, -0.229]} rotation={[Math.PI / 2, 0, 0]} scale={32.292} />
      <mesh geometry={nodes.model_5.geometry} material={materials.PaletteMaterial001} position={[-63.417, 151.9, 10.822]} rotation={[Math.PI / 2, 0, 0]} scale={220.945} />
      <mesh geometry={nodes.model_6.geometry} material={materials['Material.008']} position={[-174.232, 41.871, 6.717]} rotation={[Math.PI / 2, 0, 0]} scale={118.409} />
      <mesh geometry={nodes.model_7.geometry} material={materials['Material.046']} position={[-132.119, 148.79, 98.652]} rotation={[Math.PI / 2, 0, 0]} scale={19.644} />
      <mesh geometry={nodes.model_8.geometry} material={materials['Material.012']} position={[-144.078, 143.099, 121.483]} rotation={[Math.PI / 2, 0, 0]} scale={38.058} />
      <mesh geometry={nodes.model_9.geometry} material={materials['Material.034']} position={[-179.832, 145.092, -106.768]} rotation={[Math.PI / 2, 0, 0]} scale={70.889} />
      <mesh geometry={nodes.model_10.geometry} material={materials['Material.049']} position={[-199.007, 150.909, -69.771]} rotation={[Math.PI / 2, 0, 0]} scale={30.968} />
      <mesh geometry={nodes.model_11.geometry} material={materials['Material.007']} position={[-73.09, 93.235, 64.102]} rotation={[Math.PI / 2, 0, 0]} scale={98.115} />
      <mesh geometry={nodes.model_12.geometry} material={materials['Material.022']} position={[-147.343, 121.254, -12.906]} rotation={[Math.PI / 2, 0, 0]} scale={40.085} />
      <mesh geometry={nodes.model_13.geometry} material={materials['Material.017']} position={[80.836, -4.138, 10.906]} rotation={[Math.PI / 2, 0, 0]} scale={385.47} />
      <mesh geometry={nodes.model_14.geometry} material={materials['Material.011']} position={[-32.985, 84.711, 119.004]} rotation={[Math.PI / 2, 0, 0]} scale={209.707} />
      <mesh geometry={nodes.model_15.geometry} material={nodes.model_15.material} position={[68.731, 156.723, 7.736]} rotation={[Math.PI / 2, 0, 0]} scale={397.577} />
      <mesh geometry={nodes.model_16.geometry} material={materials['Material.009']} position={[-27.7, 62.667, 79.3]} rotation={[Math.PI / 2, 0, 0]} scale={262.481} />
      <mesh geometry={nodes.model_17.geometry} material={materials['Material.030']} position={[-180.849, 84.58, -31.021]} rotation={[Math.PI / 2, 0, 0]} scale={179.752} />
      <mesh geometry={nodes.model_18.geometry} material={materials['Material.025']} position={[34.43, 116.319, 168.408]} rotation={[Math.PI / 2, 0, 0]} scale={28.922} />
      <mesh geometry={nodes.model_19.geometry} material={materials['Material.045']} position={[32.586, 117.902, 186.434]} rotation={[Math.PI / 2, 0, 0]} scale={25.403} />
      <mesh geometry={nodes.model_20.geometry} material={materials['Material.059']} position={[91.84, 106.388, 207.457]} rotation={[Math.PI / 2, 0, 0]} scale={27.732} />
      <mesh geometry={nodes.model_21.geometry} material={materials['Material.040']} position={[-112.519, 71.945, 9.548]} rotation={[Math.PI / 2, 0, 0]} scale={165.279} />
      <mesh geometry={nodes.model_22.geometry} material={materials['Material.013']} position={[-46.539, 62.635, 15.138]} rotation={[Math.PI / 2, 0, 0]} scale={212.998} />
      <mesh geometry={nodes.model_23.geometry} material={materials['Material.041']} position={[-46.039, 80.89, 13.98]} rotation={[Math.PI / 2, 0, 0]} scale={212.214} />
      <mesh geometry={nodes.model_24.geometry} material={materials['Material.057']} position={[50.647, 161.433, 215.642]} rotation={[Math.PI / 2, 0, 0]} scale={46.06} />
      <mesh geometry={nodes.model_25.geometry} material={materials['Material.024']} position={[-9.284, 128.25, 198.949]} rotation={[Math.PI / 2, 0, 0]} scale={31.617} />
      <mesh geometry={nodes.model_27.geometry} material={materials.PaletteMaterial002} position={[-131.309, 117.344, -52.376]} rotation={[Math.PI / 2, 0, 0]} scale={96.281} />
      <mesh geometry={nodes.model_28.geometry} material={materials.PaletteMaterial003} position={[-20.911, 145.005, 45.652]} rotation={[Math.PI / 2, 0, 0]} scale={191.594} />
      <mesh geometry={nodes.model_29.geometry} material={materials['Material.055']} position={[35.765, 131.191, 24.567]} rotation={[Math.PI / 2, 0, 0]} scale={211.26} />
      <mesh geometry={nodes.model_30.geometry} material={materials['Material.062']} position={[72.718, 156.841, 5.614]} rotation={[Math.PI / 2, 0, 0]} scale={394.302} />
      <mesh geometry={nodes.model_31.geometry} material={materials['Material.072']} position={[-80.389, 63.378, -0.9]} rotation={[Math.PI / 2, 0, 0]} scale={183.053} />
      <mesh geometry={nodes.model_35.geometry} material={materials['Material.054']} position={[18.598, 99.652, 4.461]} rotation={[Math.PI / 2, 0, 0]} scale={230.73} />
      <mesh geometry={nodes.model_36.geometry} material={nodes.model_36.material} position={[8.564, 159.355, 16.289]} rotation={[Math.PI / 2, 0, 0]} scale={213.631} />
      <mesh geometry={nodes.model_37.geometry} material={materials['Material.051']} position={[-159.889, 146.639, -156.478]} rotation={[Math.PI / 2, 0, 0]} scale={21.859} />
      <mesh geometry={nodes.model_38.geometry} material={materials['Material.047']} position={[-174.602, 153.944, 59.828]} rotation={[Math.PI / 2, 0, 0]} scale={20.495} />
      <mesh geometry={nodes.model_39.geometry} material={materials['Material.026']} position={[77.228, 289.767, 13.898]} rotation={[Math.PI / 2, 0, 0]} scale={184.805} />
      <mesh geometry={nodes.model_42.geometry} material={materials['Material.053']} position={[-148.373, 118.796, -55.433]} rotation={[Math.PI / 2, 0, 0]} scale={104.397} />
      <mesh geometry={nodes.model_44.geometry} material={materials['Material.002']} position={[21.957, 153.258, -173.018]} rotation={[Math.PI / 2, 0, 0]} scale={76.972} />
      <mesh geometry={nodes.model_45.geometry} material={materials['Material.006']} position={[-56.696, 295.322, 16.545]} rotation={[Math.PI / 2, 0, 0]} scale={193.181} />
      <mesh geometry={nodes.model_46.geometry} material={materials['Material.067']} position={[-58.316, 81.969, 167.509]} rotation={[Math.PI / 2, 0, 0]} scale={67.538} />
      <mesh geometry={nodes.model_47.geometry} material={materials['Material.070']} position={[55.064, -3.534, -8.771]} rotation={[Math.PI / 2, 0, 0]} scale={140.108} />
      <mesh geometry={nodes.model_48.geometry} material={materials['Material.068']} position={[5.783, 130.073, 19.443]} rotation={[Math.PI / 2, 0, 0]} scale={207.785} />
      <mesh geometry={nodes.model_50.geometry} material={materials['Material.039']} position={[-58.288, 56.394, -6.674]} rotation={[Math.PI / 2, 0, 0]} scale={248.036} />
      <mesh geometry={nodes.model_52.geometry} material={materials['Material.063']} position={[102.369, 45.566, 184]} rotation={[Math.PI / 2, 0, 0]} scale={131.146} />
      <mesh geometry={nodes.model_53.geometry} material={materials['Material.003']} position={[80.836, 149.78, 7.736]} rotation={[Math.PI / 2, 0, 0]} scale={385.47} />
      <mesh geometry={nodes.model_54.geometry} material={materials['Material.061']} position={[-34.725, 149.78, -207.504]} rotation={[Math.PI / 2, 0, 0]} scale={269.909} />
      <mesh geometry={nodes.model_55.geometry} material={materials['Material.015']} position={[107.46, 84.247, -155.106]} rotation={[Math.PI / 2, 0, 0]} scale={86.002} />
      <mesh geometry={nodes.model_56.geometry} material={materials['Material.038']} position={[-138.277, 124.509, 54.982]} rotation={[Math.PI / 2, 0, 0]} scale={8.05} />
      <mesh geometry={nodes.model_57.geometry} material={materials['Material.037']} position={[-142.557, 121.272, -81.613]} rotation={[Math.PI / 2, 0, 0]} scale={12.765} />
      <mesh geometry={nodes.model_58.geometry} material={materials['Material.016']} position={[180.908, 81.398, -160.834]} rotation={[Math.PI / 2, 0, 0]} scale={83.152} />
      <mesh geometry={nodes.model_59.geometry} material={materials['Material.020']} position={[-135.405, 123.628, 59.524]} rotation={[Math.PI / 2, 0, 0]} scale={15.51} />
      <mesh geometry={nodes.model_61.geometry} material={materials['Material.058']} position={[119.608, 189.505, -173.9]} rotation={[Math.PI / 2, 0, 0]} scale={40.496} />
      <mesh geometry={nodes.model_62.geometry} material={materials['Material.031']} position={[18.035, 95.52, -173.14]} rotation={[Math.PI / 2, 0, 0]} scale={99.212} />
      <mesh geometry={nodes.model_64.geometry} material={materials['Material.056']} position={[-58.269, 72.058, 176.248]} rotation={[Math.PI / 2, 0, 0]} scale={76.391} />
      <mesh geometry={nodes.model_65.geometry} material={materials['Material.044']} position={[86.609, 100.233, 146.473]} rotation={[Math.PI / 2, 0, 0]} scale={4.656} />
      <mesh geometry={nodes.model_66.geometry} material={materials['Material.004']} position={[81.022, 151.494, -46.939]} rotation={[Math.PI / 2, 0, 0]} scale={385.768} />
      <mesh geometry={nodes.model_72.geometry} material={materials['Material.079']} position={[81.371, 22.616, 7.736]} rotation={[Math.PI / 2, 0, 0]} scale={384.957} />
      <mesh geometry={nodes.model_74.geometry} material={materials['Material.060']} position={[-235.766, 224.845, -24.518]} rotation={[Math.PI / 2, 0, 0]} scale={72.75} />
      <mesh geometry={nodes.model_75.geometry} material={materials['Material.052']} position={[-231.783, 221.785, -24.518]} rotation={[Math.PI / 2, 0, 0]} scale={65.65} />
      <mesh geometry={nodes.model_76.geometry} material={materials['Material.036']} position={[-168.905, 43.682, -90.386]} rotation={[Math.PI / 2, 0, 0]} scale={37.544} />
      <mesh geometry={nodes.model_77.geometry} material={materials['Material.010']} position={[-183.972, 43.043, -82.788]} rotation={[Math.PI / 2, 0, 0]} scale={31.873} />
      <mesh geometry={nodes.model_80.geometry} material={materials['Material.042']} position={[-176.934, 37.631, -90.937]} rotation={[Math.PI / 2, 0, 0]} scale={9.343} />
      <mesh geometry={nodes.model_81.geometry} material={materials['Material.050']} position={[-187.632, 150.274, -120.693]} rotation={[Math.PI / 2, 0, 0]} scale={20.968} />
      <mesh geometry={nodes.model_82.geometry} material={materials['Material.005']} position={[-239.497, 258.996, -28.327]} rotation={[Math.PI / 2, 0, 0]} scale={66.006} />
      <mesh geometry={nodes.model_83.geometry} material={materials['Material.033']} position={[-123.08, 165.411, -196.651]} rotation={[Math.PI / 2, 0, 0]} scale={6.783} />
      <mesh geometry={nodes.model_84.geometry} material={materials['Material.018']} position={[-164.934, 123.711, 37.465]} rotation={[Math.PI / 2, 0, 0]} scale={15.573} />
      <mesh geometry={nodes.model_85.geometry} material={materials['Material.001']} position={[-145.873, 118.848, 35.262]} rotation={[Math.PI / 2, 0, 0]} scale={7.968} />
      <mesh geometry={nodes.model_86.geometry} material={materials['Material.021']} position={[-257.703, 127.406, 190.62]} rotation={[Math.PI / 2, 0, 0]} scale={132.474} />
      <mesh geometry={nodes.model_87.geometry} material={materials['Material.064']} position={[-157.547, 26.82, -142.543]} rotation={[Math.PI / 2, 0, 0]} scale={16.713} />
      <mesh geometry={nodes.model_129.geometry} material={materials.PaletteMaterial005} position={[-163.739, 63.41, -10.782]} rotation={[Math.PI / 2, 0, 0]} scale={63.558} />
      <mesh geometry={nodes.model_150.geometry} material={materials['Material.066']} position={[-76.059, 151.905, 13.71]} rotation={[Math.PI / 2, 0, 0]} scale={221.439} />
      <mesh geometry={nodes.model_169.geometry} material={materials['Material.075']} position={[71.061, 183.206, 15.45]} rotation={[Math.PI / 2, 0, 0]} scale={159.201} />
      <instancedMesh args={[nodes.model_68.geometry, materials.PaletteMaterial004, 6]} instanceMatrix={nodes.model_68.instanceMatrix} />
      <instancedMesh args={[nodes.model_89.geometry, nodes.model_89.material, 178]} instanceMatrix={nodes.model_89.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/models/hackers_basement_opt-transformed.glb')
