/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/matrix_2_opt.glb -t -T -d -o public/models/Matrix2.tsx 
Files: public/models/matrix_2_opt.glb [11.46MB] > C:\dev\portfolio-web-matrix\public\models\matrix_2_opt-transformed.glb [25.15MB] (-119%)
Author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/menger-matrix-ii-use-j-k-keys-47f2425f6a9b4509911d5686fb1227a8
Title: Menger Matrix II (Use J + K Keys)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Animation'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_27: THREE.Mesh
    Object_52: THREE.Mesh
    Object_50: THREE.Mesh
    Object_75: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
    material_0: THREE.MeshStandardMaterial
    material_2: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Matrix2(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/models/matrix_2_opt-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode" scale={0.553}>
          <group name="Sponge_0" position={[0.667, 0, 0]}>
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.material} position={[0, -0.006, 0]} scale={2.278} />
          </group>
          <group name="Sponge001_1">
            <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.material} position={[0, -0.006, 0]} scale={2.278} />
          </group>
          <group name="Sponge002_3" position={[-0.667, 0, 0]}>
            <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.material} position={[0, -0.006, 0]} scale={2.278} />
          </group>
        </group>
        <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.material_0} rotation={[0, 0, -Math.PI / 2]} scale={0.117} />
        <mesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.material_2} rotation={[0, 0, -Math.PI / 2]} scale={[3.42, 0.858, 3.42]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/matrix_2_opt-transformed.glb')
