/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/metal_spoon_opt.glb -t -T -d -o public/models/MetalSpoon.tsx 
Files: public/models/metal_spoon_opt.glb [171.39KB] > C:\dev\portfolio-web-matrix\public\models\metal_spoon_opt-transformed.glb [291.19KB] (-70%)
Author: Ryllae Sylna (https://sketchfab.com/risteralline)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bended-metal-spoon-47599b2cae5744e09ed70916697e46bb
Title: Bended metal spoon
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    SpoonMatrix_high_SpoonMatrix_high_0: THREE.Mesh
  }
  materials: {
    SpoonMatrix_high: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function MetalSpoon(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/metal_spoon_opt-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SpoonMatrix_high_SpoonMatrix_high_0.geometry} material={materials.SpoonMatrix_high} position={[0.025, -0.027, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.092} />
    </group>
  )
}

useGLTF.preload('/models/metal_spoon_opt-transformed.glb')
