/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/neo_shades_opt.glb -t -T -d -o public/models/NeoShades.tsx 
Files: public/models/neo_shades_opt.glb [2.75MB] > C:\dev\portfolio-web-matrix\public\models\neo_shades_opt-transformed.glb [2.27MB] (18%)
Author: Fridge (https://sketchfab.com/youssefdarwish01)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/neo-shades-9c245663fb2141aeba813ca0d7d9bb07
Title: Neo Shades
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    NeoJacket_NeoJacket_0: THREE.Mesh
    NeoGlasses_NeoShades_0: THREE.Mesh
  }
  materials: {
    NeoJacket: THREE.MeshStandardMaterial
    NeoShades: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function NeoShades(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/neo_shades_opt-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.NeoJacket_NeoJacket_0.geometry} material={materials.NeoJacket} position={[1.072, 0.589, 1.656]} scale={3.518} />
      <mesh geometry={nodes.NeoGlasses_NeoShades_0.geometry} material={materials.NeoShades} position={[0.98, 3.737, 2.035]} rotation={[1.762, 0, Math.PI]} scale={1.088} />
    </group>
  )
}

useGLTF.preload('/models/neo_shades_opt-transformed.glb')
