/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/panasonic_rc_6088_am_opt.glb -t -T -d -o public/models/PanasonicRc6088Am.tsx 
Files: public/models/panasonic_rc_6088_am_opt.glb [519.17KB] > C:\dev\portfolio-web-matrix\public\models\panasonic_rc_6088_am_opt-transformed.glb [453.78KB] (13%)
Author: Sirenko (https://sketchfab.com/sirenko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/panasonic-rc-6088-am-72801a6b5e8044a19fd14498493efc14
Title: Panasonic RC 6088 AM
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
  }
  materials: {
    Material__25: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function PanasonicRc6088Am(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/panasonic_rc_6088_am_opt-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Material__25} />
    </group>
  )
}

useGLTF.preload('/models/panasonic_rc_6088_am_opt-transformed.glb')
