/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/white_room_opt.glb -t -T -d -o public/models/WhiteRoom.tsx 
Files: public/models/white_room_opt.glb [7.14MB] > C:\dev\portfolio-web-matrix\public\models\white_room_opt-transformed.glb [5.72MB] (20%)
Author: commonfactory (https://sketchfab.com/commonfactory)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-matrix-white-room-063bcbf52b4e489e8920f6ff596238c5
Title: The Matrix White Room
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Animation'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_56: THREE.Mesh
    Object_58: THREE.Mesh
    Object_60: THREE.Mesh
    Object_62: THREE.Mesh
    Object_64: THREE.Mesh
    Object_66: THREE.Mesh
    Object_68: THREE.Mesh
    Object_70: THREE.Mesh
    Object_72: THREE.Mesh
    Object_74: THREE.Mesh
    Object_76: THREE.Mesh
    Object_78: THREE.Mesh
    Object_80: THREE.Mesh
    Object_82: THREE.Mesh
    Object_84: THREE.Mesh
    Object_86: THREE.Mesh
    Object_88: THREE.Mesh
    Object_90: THREE.Mesh
    Object_92: THREE.Mesh
    Object_94: THREE.Mesh
    Object_96: THREE.Mesh
    Object_98: THREE.Mesh
    Object_100: THREE.Mesh
    Object_102: THREE.Mesh
    Object_104: THREE.Mesh
    Object_106: THREE.Mesh
    Object_108: THREE.Mesh
    Object_110: THREE.Mesh
    Object_112: THREE.Mesh
    Object_114: THREE.Mesh
    Object_116: THREE.Mesh
    Object_118: THREE.Mesh
    Object_120: THREE.Mesh
    Object_122: THREE.Mesh
    Object_124: THREE.Mesh
    Object_126: THREE.Mesh
    Object_128: THREE.Mesh
    Object_130: THREE.Mesh
    Object_132: THREE.Mesh
    Object_134: THREE.Mesh
    Object_136: THREE.Mesh
    Object_138: THREE.Mesh
    Object_140: THREE.Mesh
    Object_142: THREE.Mesh
    Object_144: THREE.Mesh
    Object_146: THREE.Mesh
    Object_148: THREE.Mesh
    Object_150: THREE.Mesh
    Object_152: THREE.Mesh
    Object_154: THREE.Mesh
    Object_156: THREE.Mesh
    Object_158: THREE.Mesh
    Object_160: THREE.Mesh
    Object_162: THREE.Mesh
    Object_164: THREE.Mesh
    Object_166: THREE.Mesh
    Object_168: THREE.Mesh
    Object_170: THREE.Mesh
    Object_172: THREE.Mesh
    Object_174: THREE.Mesh
    Object_176: THREE.Mesh
    Object_178: THREE.Mesh
    Object_180: THREE.Mesh
    Object_182: THREE.Mesh
    Object_184: THREE.Mesh
    Object_186: THREE.Mesh
    Object_188: THREE.Mesh
    Object_190: THREE.Mesh
    Object_192: THREE.Mesh
    Object_194: THREE.Mesh
    Object_196: THREE.Mesh
    Object_198: THREE.Mesh
    Object_200: THREE.Mesh
    Object_202: THREE.Mesh
    Object_204: THREE.Mesh
    Object_206: THREE.Mesh
    Object_208: THREE.Mesh
    Object_210: THREE.Mesh
    Object_212: THREE.Mesh
    Object_214: THREE.Mesh
    Object_216: THREE.Mesh
    Object_218: THREE.Mesh
    Object_220: THREE.Mesh
    Object_222: THREE.Mesh
    Object_224: THREE.Mesh
    Object_226: THREE.Mesh
    Object_228: THREE.Mesh
    Object_230: THREE.Mesh
    Object_232: THREE.Mesh
    Object_234: THREE.Mesh
    Object_236: THREE.Mesh
    Object_238: THREE.Mesh
    Object_240: THREE.Mesh
    Object_242: THREE.Mesh
    Object_244: THREE.Mesh
    Object_246: THREE.Mesh
    Object_248: THREE.Mesh
    Object_250: THREE.Mesh
    Object_252: THREE.Mesh
    Object_254: THREE.Mesh
    Object_256: THREE.Mesh
    Object_258: THREE.Mesh
    Object_260: THREE.Mesh
    Object_262: THREE.Mesh
    Object_264: THREE.Mesh
    Object_266: THREE.Mesh
    Object_268: THREE.Mesh
    Object_270: THREE.Mesh
    Object_272: THREE.Mesh
    Object_274: THREE.Mesh
    Object_276: THREE.Mesh
    Object_278: THREE.Mesh
    Object_280: THREE.Mesh
    Object_282: THREE.Mesh
    Object_284: THREE.Mesh
    Object_286: THREE.Mesh
    Object_288: THREE.Mesh
    Object_290: THREE.Mesh
    Object_292: THREE.Mesh
    Object_294: THREE.Mesh
    Object_296: THREE.Mesh
    Object_298: THREE.Mesh
    Object_300: THREE.Mesh
    Object_302: THREE.Mesh
    Object_304: THREE.Mesh
    Object_306: THREE.Mesh
    Object_308: THREE.Mesh
    Object_310: THREE.Mesh
    Object_312: THREE.Mesh
    Object_314: THREE.Mesh
    Object_316: THREE.Mesh
    Object_318: THREE.Mesh
    Object_320: THREE.Mesh
    Object_322: THREE.Mesh
    Object_324: THREE.Mesh
    Object_326: THREE.Mesh
    Object_328: THREE.Mesh
    Object_330: THREE.Mesh
    Object_332: THREE.Mesh
    Object_334: THREE.Mesh
    Object_336: THREE.Mesh
    Object_338: THREE.Mesh
    Object_340: THREE.Mesh
    Object_342: THREE.Mesh
    Object_344: THREE.Mesh
    Object_346: THREE.Mesh
    Object_348: THREE.Mesh
    Object_350: THREE.Mesh
    Object_352: THREE.Mesh
    Object_354: THREE.Mesh
    Object_356: THREE.Mesh
    Object_358: THREE.Mesh
    Object_360: THREE.Mesh
    Object_362: THREE.Mesh
    Object_364: THREE.Mesh
    Object_366: THREE.Mesh
    Object_368: THREE.Mesh
    Object_370: THREE.Mesh
    Object_372: THREE.Mesh
    Object_374: THREE.Mesh
    Object_376: THREE.Mesh
    Object_378: THREE.Mesh
    Object_380: THREE.Mesh
    Object_382: THREE.Mesh
    Object_384: THREE.Mesh
    Object_386: THREE.Mesh
    Object_388: THREE.Mesh
    Object_390: THREE.Mesh
    Object_392: THREE.Mesh
    Object_394: THREE.Mesh
    Object_396: THREE.Mesh
    Object_398: THREE.Mesh
    Object_400: THREE.Mesh
    Object_402: THREE.Mesh
    Object_407: THREE.Mesh
    Object_410: THREE.Mesh
    Object_413: THREE.Mesh
    Object_427: THREE.Mesh
    Object_455: THREE.Mesh
  }
  materials: {
    Merged_materials: THREE.MeshStandardMaterial
    ['Screen.137']: THREE.MeshStandardMaterial
    ['Screen.137_0']: THREE.MeshStandardMaterial
    ['Screen.137_1']: THREE.MeshStandardMaterial
    ['Screen.137_2']: THREE.MeshStandardMaterial
    ['Screen.137_3']: THREE.MeshStandardMaterial
    ['Screen.137_4']: THREE.MeshStandardMaterial
    ['Screen.137_5']: THREE.MeshStandardMaterial
    ['Screen.137_6']: THREE.MeshStandardMaterial
    ['Screen.137_7']: THREE.MeshStandardMaterial
    ['Screen.137_8']: THREE.MeshStandardMaterial
    ['Screen.137_9']: THREE.MeshStandardMaterial
    ['Screen.137_10']: THREE.MeshStandardMaterial
    ['Screen.137_11']: THREE.MeshStandardMaterial
    ['Screen.137_12']: THREE.MeshStandardMaterial
    ['Screen.137_13']: THREE.MeshStandardMaterial
    ['Screen.137_14']: THREE.MeshStandardMaterial
    ['Screen.137_15']: THREE.MeshStandardMaterial
    ['Screen.137_16']: THREE.MeshStandardMaterial
    ['Screen.137_17']: THREE.MeshStandardMaterial
    ['Screen.137_18']: THREE.MeshStandardMaterial
    ['Screen.137_19']: THREE.MeshStandardMaterial
    ['Screen.137_20']: THREE.MeshStandardMaterial
    ['Screen.137_21']: THREE.MeshStandardMaterial
    ['Screen.137_22']: THREE.MeshStandardMaterial
    ['Screen.137_23']: THREE.MeshStandardMaterial
    ['Screen.137_24']: THREE.MeshStandardMaterial
    ['Screen.137_25']: THREE.MeshStandardMaterial
    ['Screen.137_26']: THREE.MeshStandardMaterial
    ['Screen.137_27']: THREE.MeshStandardMaterial
    ['Screen.137_28']: THREE.MeshStandardMaterial
    ['Screen.137_29']: THREE.MeshStandardMaterial
    ['Screen.137_30']: THREE.MeshStandardMaterial
    ['Screen.137_31']: THREE.MeshStandardMaterial
    ['Screen.137_32']: THREE.MeshStandardMaterial
    ['Screen.137_33']: THREE.MeshStandardMaterial
    ['Screen.137_34']: THREE.MeshStandardMaterial
    ['Screen.137_35']: THREE.MeshStandardMaterial
    ['Screen.137_36']: THREE.MeshStandardMaterial
    ['Screen.137_37']: THREE.MeshStandardMaterial
    ['Screen.137_38']: THREE.MeshStandardMaterial
    ['Screen.137_39']: THREE.MeshStandardMaterial
    ['Screen.137_40']: THREE.MeshStandardMaterial
    ['Screen.137_41']: THREE.MeshStandardMaterial
    ['Screen.137_42']: THREE.MeshStandardMaterial
    ['Screen.137_43']: THREE.MeshStandardMaterial
    ['Screen.137_44']: THREE.MeshStandardMaterial
    ['Screen.137_45']: THREE.MeshStandardMaterial
    ['Screen.137_46']: THREE.MeshStandardMaterial
    ['Screen.137_47']: THREE.MeshStandardMaterial
    ['Screen.137_48']: THREE.MeshStandardMaterial
    ['Screen.137_49']: THREE.MeshStandardMaterial
    ['Screen.137_50']: THREE.MeshStandardMaterial
    ['Screen.137_51']: THREE.MeshStandardMaterial
    ['Screen.137_52']: THREE.MeshStandardMaterial
    ['Screen.137_53']: THREE.MeshStandardMaterial
    ['Screen.137_54']: THREE.MeshStandardMaterial
    ['Screen.137_55']: THREE.MeshStandardMaterial
    ['Screen.137_56']: THREE.MeshStandardMaterial
    ['Screen.137_57']: THREE.MeshStandardMaterial
    ['Screen.137_58']: THREE.MeshStandardMaterial
    ['Screen.137_59']: THREE.MeshStandardMaterial
    ['Screen.137_60']: THREE.MeshStandardMaterial
    ['Screen.137_61']: THREE.MeshStandardMaterial
    ['Screen.137_62']: THREE.MeshStandardMaterial
    ['Screen.137_63']: THREE.MeshStandardMaterial
    ['Screen.137_64']: THREE.MeshStandardMaterial
    ['Screen.137_65']: THREE.MeshStandardMaterial
    ['Screen.137_66']: THREE.MeshStandardMaterial
    ['Screen.137_67']: THREE.MeshStandardMaterial
    ['Screen.137_68']: THREE.MeshStandardMaterial
    ['Screen.137_69']: THREE.MeshStandardMaterial
    ['Screen.137_70']: THREE.MeshStandardMaterial
    ['Screen.137_71']: THREE.MeshStandardMaterial
    ['Screen.137_72']: THREE.MeshStandardMaterial
    ['Screen.137_73']: THREE.MeshStandardMaterial
    ['Screen.137_74']: THREE.MeshStandardMaterial
    ['Screen.137_75']: THREE.MeshStandardMaterial
    ['Screen.137_76']: THREE.MeshStandardMaterial
    ['Screen.137_77']: THREE.MeshStandardMaterial
    ['Screen.137_78']: THREE.MeshStandardMaterial
    ['Screen.137_79']: THREE.MeshStandardMaterial
    ['Screen.137_80']: THREE.MeshStandardMaterial
    ['Screen.137_81']: THREE.MeshStandardMaterial
    ['Screen.137_82']: THREE.MeshStandardMaterial
    ['Screen.137_83']: THREE.MeshStandardMaterial
    ['Screen.137_84']: THREE.MeshStandardMaterial
    ['Screen.137_85']: THREE.MeshStandardMaterial
    ['Screen.137_86']: THREE.MeshStandardMaterial
    ['Screen.137_87']: THREE.MeshStandardMaterial
    ['Screen.137_88']: THREE.MeshStandardMaterial
    ['Screen.137_89']: THREE.MeshStandardMaterial
    ['Screen.137_90']: THREE.MeshStandardMaterial
    ['Screen.137_91']: THREE.MeshStandardMaterial
    ['Screen.137_92']: THREE.MeshStandardMaterial
    ['Radiola.001']: THREE.MeshStandardMaterial
    ['Radiola.001_0']: THREE.MeshStandardMaterial
    ['Radiola.001_1']: THREE.MeshStandardMaterial
    ['Radiola.001_2']: THREE.MeshStandardMaterial
    ['Radiola.001_3']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function WhiteRoom(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/models/white_room_opt-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="TV_Screen001_0" position={[0.01, 0, 0]} scale={[0.882, 1, 1]}>
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen002_1" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen003_2" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen004_3" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen005_4" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen006_5" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen007_6" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials['Screen.137']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen008_7" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials['Screen.137_0']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen009_8" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials['Screen.137_1']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen010_9" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials['Screen.137_2']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen011_10" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen012_11" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen013_12" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen014_13" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen015_14" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen016_15" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen017_16" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen018_17" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen019_18" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen020_19" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen021_20" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen022_21" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen023_22" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen024_23" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen025_24" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen026_25" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen027_26" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen028_27" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen029_28" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen030_29" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen031_30" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen032_31" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen033_32" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen034_33" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen035_34" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen036_35" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen037_36" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen038_37" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen039_38" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen040_39" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen041_40" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen042_41" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen043_42" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen044_43" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen045_44" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen046_45" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen047_46" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen048_47" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen049_48" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen050_49" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen051_50" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen052_51" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen053_52" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen054_53" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen055_54" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen056_55" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen057_56" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen058_57" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen059_58" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen060_59" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen061_60" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen062_61" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen063_62" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen064_63" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen065_64" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen066_65" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen067_66" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen068_67" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_138" geometry={nodes.Object_138.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen069_68" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen070_69" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen071_70" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen072_71" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen073_72" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen074_73" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_150" geometry={nodes.Object_150.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen075_74" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen076_75" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen077_76" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen078_77" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen079_78" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen080_79" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_162" geometry={nodes.Object_162.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen081_80" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_164" geometry={nodes.Object_164.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen082_81" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_166" geometry={nodes.Object_166.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen083_82" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_168" geometry={nodes.Object_168.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen084_83" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen085_84" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen086_85" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_174" geometry={nodes.Object_174.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen087_86" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_176" geometry={nodes.Object_176.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen088_87" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_178" geometry={nodes.Object_178.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen089_88" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_180" geometry={nodes.Object_180.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen090_89" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_182" geometry={nodes.Object_182.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen091_90" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_184" geometry={nodes.Object_184.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen092_91" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_186" geometry={nodes.Object_186.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen093_92" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_188" geometry={nodes.Object_188.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen094_93" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_190" geometry={nodes.Object_190.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen095_94" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_192" geometry={nodes.Object_192.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen096_95" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_194" geometry={nodes.Object_194.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen097_96" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_196" geometry={nodes.Object_196.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen098_97" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_198" geometry={nodes.Object_198.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen099_98" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_200" geometry={nodes.Object_200.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen100_99" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_202" geometry={nodes.Object_202.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen101_100" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_204" geometry={nodes.Object_204.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen102_101" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_206" geometry={nodes.Object_206.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen103_102" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_208" geometry={nodes.Object_208.geometry} material={materials['Screen.137_3']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen104_103" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_210" geometry={nodes.Object_210.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen105_104" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_212" geometry={nodes.Object_212.geometry} material={materials['Screen.137_4']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen106_105" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_214" geometry={nodes.Object_214.geometry} material={materials['Screen.137_5']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen107_106" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_216" geometry={nodes.Object_216.geometry} material={materials['Screen.137_6']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen108_107" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_218" geometry={nodes.Object_218.geometry} material={materials['Screen.137_7']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen109_108" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_220" geometry={nodes.Object_220.geometry} material={materials['Screen.137_8']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen110_109" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_222" geometry={nodes.Object_222.geometry} material={materials['Screen.137_9']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen111_110" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_224" geometry={nodes.Object_224.geometry} material={materials['Screen.137_10']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen112_111" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_226" geometry={nodes.Object_226.geometry} material={materials['Screen.137_11']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen113_112" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_228" geometry={nodes.Object_228.geometry} material={materials['Screen.137_12']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen114_113" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_230" geometry={nodes.Object_230.geometry} material={materials['Screen.137_13']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen115_114" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_232" geometry={nodes.Object_232.geometry} material={materials['Screen.137_14']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen116_115" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_234" geometry={nodes.Object_234.geometry} material={materials['Screen.137_15']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen117_116" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_236" geometry={nodes.Object_236.geometry} material={materials['Screen.137_16']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen118_117" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_238" geometry={nodes.Object_238.geometry} material={materials['Screen.137_17']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen119_118" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_240" geometry={nodes.Object_240.geometry} material={materials['Screen.137_18']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen120_119" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_242" geometry={nodes.Object_242.geometry} material={materials['Screen.137_19']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen121_120" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_244" geometry={nodes.Object_244.geometry} material={materials['Screen.137_20']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen122_121" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_246" geometry={nodes.Object_246.geometry} material={materials['Screen.137_21']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen123_122" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_248" geometry={nodes.Object_248.geometry} material={materials['Screen.137_22']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen124_123" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_250" geometry={nodes.Object_250.geometry} material={materials['Screen.137_23']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen125_124" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_252" geometry={nodes.Object_252.geometry} material={materials['Screen.137_24']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen126_125" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_254" geometry={nodes.Object_254.geometry} material={materials['Screen.137_25']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen127_126" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_256" geometry={nodes.Object_256.geometry} material={materials['Screen.137_26']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen128_127" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_258" geometry={nodes.Object_258.geometry} material={materials['Screen.137_27']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen129_128" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_260" geometry={nodes.Object_260.geometry} material={materials['Screen.137_28']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen130_129" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_262" geometry={nodes.Object_262.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen131_130" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_264" geometry={nodes.Object_264.geometry} material={materials['Screen.137_29']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen132_131" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_266" geometry={nodes.Object_266.geometry} material={materials['Screen.137_30']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen133_132" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_268" geometry={nodes.Object_268.geometry} material={materials['Screen.137_31']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen134_133" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_270" geometry={nodes.Object_270.geometry} material={materials['Screen.137_32']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen135_134" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_272" geometry={nodes.Object_272.geometry} material={materials['Screen.137_33']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen136_135" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_274" geometry={nodes.Object_274.geometry} material={materials['Screen.137_34']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen137_136" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_276" geometry={nodes.Object_276.geometry} material={materials['Screen.137_35']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen138_137" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_278" geometry={nodes.Object_278.geometry} material={materials['Screen.137_36']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen139_138" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_280" geometry={nodes.Object_280.geometry} material={materials['Screen.137_37']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen140_139" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_282" geometry={nodes.Object_282.geometry} material={materials['Screen.137_38']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen141_140" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_284" geometry={nodes.Object_284.geometry} material={materials['Screen.137_39']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen142_141" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_286" geometry={nodes.Object_286.geometry} material={materials['Screen.137_40']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen143_142" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_288" geometry={nodes.Object_288.geometry} material={materials['Screen.137_41']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen144_143" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_290" geometry={nodes.Object_290.geometry} material={materials['Screen.137_42']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen145_144" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_292" geometry={nodes.Object_292.geometry} material={materials['Screen.137_43']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen146_145" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_294" geometry={nodes.Object_294.geometry} material={materials['Screen.137_44']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen147_146" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_296" geometry={nodes.Object_296.geometry} material={materials['Screen.137_45']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen148_147" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_298" geometry={nodes.Object_298.geometry} material={materials['Screen.137_46']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen149_148" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_300" geometry={nodes.Object_300.geometry} material={materials['Screen.137_47']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen150_149" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_302" geometry={nodes.Object_302.geometry} material={materials['Screen.137_48']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen151_150" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_304" geometry={nodes.Object_304.geometry} material={materials['Screen.137_49']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen152_151" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_306" geometry={nodes.Object_306.geometry} material={materials['Screen.137_50']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen153_152" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_308" geometry={nodes.Object_308.geometry} material={materials['Screen.137_51']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen154_153" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_310" geometry={nodes.Object_310.geometry} material={materials['Screen.137_52']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen155_154" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_312" geometry={nodes.Object_312.geometry} material={materials['Screen.137_53']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen156_155" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_314" geometry={nodes.Object_314.geometry} material={materials['Screen.137_54']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen157_156" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_316" geometry={nodes.Object_316.geometry} material={materials['Screen.137_55']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen158_157" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_318" geometry={nodes.Object_318.geometry} material={materials['Screen.137_56']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen159_158" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_320" geometry={nodes.Object_320.geometry} material={materials['Screen.137_57']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen160_159" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_322" geometry={nodes.Object_322.geometry} material={materials['Screen.137_58']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen161_160" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_324" geometry={nodes.Object_324.geometry} material={materials['Screen.137_59']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen162_161" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_326" geometry={nodes.Object_326.geometry} material={materials['Screen.137_60']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen163_162" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_328" geometry={nodes.Object_328.geometry} material={materials['Screen.137_61']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen164_163" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_330" geometry={nodes.Object_330.geometry} material={materials['Screen.137_62']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen165_164" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_332" geometry={nodes.Object_332.geometry} material={materials['Screen.137_63']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen166_165" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_334" geometry={nodes.Object_334.geometry} material={materials['Screen.137_64']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen167_166" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_336" geometry={nodes.Object_336.geometry} material={materials['Screen.137_65']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen168_167" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_338" geometry={nodes.Object_338.geometry} material={materials['Screen.137_66']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen169_168" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_340" geometry={nodes.Object_340.geometry} material={materials['Screen.137_67']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen170_169" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_342" geometry={nodes.Object_342.geometry} material={materials['Screen.137_68']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen171_170" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_344" geometry={nodes.Object_344.geometry} material={materials['Screen.137_69']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen172_171" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_346" geometry={nodes.Object_346.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen173_172" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_348" geometry={nodes.Object_348.geometry} material={materials.Merged_materials} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen174_173" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_350" geometry={nodes.Object_350.geometry} material={materials['Screen.137_70']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen175_174" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_352" geometry={nodes.Object_352.geometry} material={materials['Screen.137_71']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen176_175" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_354" geometry={nodes.Object_354.geometry} material={materials['Screen.137_72']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen177_176" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_356" geometry={nodes.Object_356.geometry} material={materials['Screen.137_73']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen178_177" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_358" geometry={nodes.Object_358.geometry} material={materials['Screen.137_74']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen179_178" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_360" geometry={nodes.Object_360.geometry} material={materials['Screen.137_75']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen180_179" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_362" geometry={nodes.Object_362.geometry} material={materials['Screen.137_76']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen181_180" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_364" geometry={nodes.Object_364.geometry} material={materials['Screen.137_77']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen182_181" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_366" geometry={nodes.Object_366.geometry} material={materials['Screen.137_78']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen183_182" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_368" geometry={nodes.Object_368.geometry} material={materials['Screen.137_79']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen184_183" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_370" geometry={nodes.Object_370.geometry} material={materials['Screen.137_80']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen185_184" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_372" geometry={nodes.Object_372.geometry} material={materials['Screen.137_81']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen186_185" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_374" geometry={nodes.Object_374.geometry} material={materials['Screen.137_82']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen187_186" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_376" geometry={nodes.Object_376.geometry} material={materials['Screen.137_83']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen188_187" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_378" geometry={nodes.Object_378.geometry} material={materials['Screen.137_84']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen189_188" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_380" geometry={nodes.Object_380.geometry} material={materials['Screen.137_85']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen190_189" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_382" geometry={nodes.Object_382.geometry} material={materials['Screen.137_86']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen191_190" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_384" geometry={nodes.Object_384.geometry} material={materials['Screen.137_87']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen192_191" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_386" geometry={nodes.Object_386.geometry} material={materials['Screen.137_88']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen193_192" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_388" geometry={nodes.Object_388.geometry} material={materials['Screen.137_89']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen194_193" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_390" geometry={nodes.Object_390.geometry} material={materials['Screen.137_90']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen195_194" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_392" geometry={nodes.Object_392.geometry} material={materials['Screen.137_91']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen196_195" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_394" geometry={nodes.Object_394.geometry} material={materials['Screen.137_92']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen197_196" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_396" geometry={nodes.Object_396.geometry} material={materials['Screen.137']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen198_197" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_398" geometry={nodes.Object_398.geometry} material={materials['Screen.137_0']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen199_198" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_400" geometry={nodes.Object_400.geometry} material={materials['Screen.137_1']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
          <group name="TV_Screen200_199" position={[0.01, 0, -0.01]} scale={[0.882, 1, 1]}>
            <mesh name="Object_402" geometry={nodes.Object_402.geometry} material={materials['Screen.137_2']} position={[-0.01, 0.677, -2.013]} scale={0.295} />
          </group>
        </group>
        <mesh name="Object_407" geometry={nodes.Object_407.geometry} material={materials['Radiola.001']} position={[0.022, 0.37, -0.093]} scale={1.864} />
        <mesh name="Object_410" geometry={nodes.Object_410.geometry} material={materials['Radiola.001_0']} position={[0.022, 0.768, -0.016]} scale={1.998} />
        <mesh name="Object_413" geometry={nodes.Object_413.geometry} material={materials['Radiola.001_1']} position={[0.023, 0.477, -0.146]} scale={1.651} />
        <mesh name="Object_427" geometry={nodes.Object_427.geometry} material={materials['Radiola.001_2']} position={[0, 0.486, -2.329]} scale={0.487} />
        <mesh name="Object_455" geometry={nodes.Object_455.geometry} material={materials['Radiola.001_3']} position={[-0.12, 0.448, -1.993]} scale={0.074} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/white_room_opt-transformed.glb')
